### ISSUE TITLE
Decide what template to use

### ISSUE THREAD

**Issue by gowebUSA** [gowebUSA/MSSA-Group-Project#1]
As a shop, we want to have a front-end (customer) and a back-end (admin) to handle orders.

- [x]  As a team, decide on what template to use.
- [x]  Submit choices of template for the team to choose.

**Comment by trashg0blin** [comment]
Testing comment

**Comment by gowebUSA** [comment]
1. We will use SportStore Project
- Front-end, 3 products, no categories.
- Back-end, admin tab, order tab. Should have a link to go to fronpage.
   * Admin - just be able to delete and edit menu.
   * Order - see the order pipeline that is coming in.
      * Delete an order
      * Modify the order. delete order, change qty, change name and address and payment.
